name: delaware_test
start_date: 2020-1-31
end_date: 2020-12-31
nsimulations: 1000
dt: 0.25
dynfilter_path: data/filter.txt 

spatial_setup:
  census_year: 2016
  base_path: data
  modeled_states: 
   - DE
  setup_name: delaware_test
  geodata: geodata.csv
  mobility: mobility.txt
  popnodes: pop2010
  nodenames: geoid
  shapefile_name: shp/counties_2016_delaware_test.shp

importation: 
  census_api_key: get your own
  travel_dispersion: 3
  maximum_destinations: Inf
  dest_type : state
  dest_country : USA
  aggregate_to: airport
  cache_work: TRUE
  update_case_data: TRUE
  draw_travel_from_distribution: FALSE
  print_progress: TRUE
  travelers_threshold: 1000
  airport_cluster_distance: 80
  param_list:
    incub_mean_log: log(5.89)
    incub_sd_log: log(1.74)
    inf_period_nohosp_mean: 15
    inf_period_nohosp_sd: 5
    inf_period_hosp_mean_log: 1.23
    inf_period_hosp_sd_log: 0.79
    p_report_source: [0.05, 0.25]
    shift_incid_days: -10
    delta: 1

seeding:
  method: FolderDraw
  folder_path: importation/delaware_test/
  
seir:
  parameters:
    sigma: 1 / 5.2
    gamma:
      distribution: uniform
      low: 1 / 6
      high: 1 / 2.6
    R0s:
      distribution: uniform
      low: 2
      high: 3

interventions:
  scenarios:
    - MyScenario1
    - MyScenario2
    - MyScenario3
  settings:
    None:
      template: ReduceR0
      period_start_date: 2020-5-15
      period_end_date: 2020-12-31
      value:
        distribution: fixed
        value: 0
    Wuhan:
      template: ReduceR0
      period_start_date: 2020-03-19
      period_end_date: 2020-05-14
      value:
        distribution: uniform
        low: .14
        high: .33
    Influenza1918:
      template: ReduceR0
      period_start_date: 2020-05-15
      period_end_date: 2020-12-31
      value:
        distribution: uniform
        low: .44
        high: .65
    SchoolClosure:
      template: ReduceR0
      period_start_date: 2020-03-13
      period_end_date: 2020-03-19
      value:
        distribution: truncnorm
        a: .16
        b: .30
        mean: .18
        sd: .05
    TestIsolate:
      template: ReduceR0
      period_start_date: 2020-05-15
      period_end_date: 2020-12-31
      value:
        distribution: uniform
        low: .48
        high: .76
    # This scenario has statewide school closures from March 13-19 followed by a statewide stay-at-home policy from March 19 through May 14. All interventions are then removed (back to worst-case uncontrolled transmission) starting May 15.
    MyScenario1:
      template: Stacked
      scenarios:
        - SchoolClosure
        - Wuhan
        - None
    # This scenario has statewide school closures from March 13-19 followed by a statewide stay-at-home policy from March 19 through May 14. From May 15 through December 31, there is a targeted test and isolate strategy similar to that implemented in South Korea.
    MyScenario2:
      template: Stacked
      scenarios:
        - SchoolClosure
        - Wuhan
        - TestIsolate
    # This scenario has statewide school closures from March 13-19 followed by a statewide stay-at-home policy from March 19 through May 14. From May 15 through December 31, there is moderately restrictive social distancing similar to that in US cities during the 1918 influenza pandemic.
    MyScenario3:
      template: Stacked
      scenarios:
        - SchoolClosure
        - Wuhan
        - Influenza1918
        
hospitalization:
  paths:
    output_path: hospitalization
  parameters:
    time_hosp: [1.23, 0.79]
    time_disch: [log(11.5), log(1.22)]
    time_death: [log(11.25), log(1.15)]
    time_ICU: [log(8.25), log(2.2)]
    time_ICUdur: [log(16), log(2.96)]
    time_vent: [log(10.5), log((10.5-8)/1.35)]
    p_death: [.0025, .005, .01]
    p_death_names: ["low","med","high"]
    p_death_rate: 0.1
    p_ICU: 0.32
    p_vent: 0.15

report:
  data_settings:
    pop_year: 2016
  plot_settings:
    plot_intervention: TRUE
    parameters_to_display:
      sigma:
        type: seir
        distribution: exp
        formal_name: Incubation Period
        transform: invert
        xlab: Days since symptom onset
      gamma:
        type: seir
        distribution: gamma
        formal_name: Duration of Infectiousness
        transform: invert
        xlab: Days since symptom onset
      time_hosp:
        type: hospitalization
        distribution: lnormal
        formal_name: Time to Hospitalization
        xlab: Days since symptom onset
        xlim: [0,100]
      time_disch:
        type: hospitalization
        distribution: lnormal
        formal_name: Time to Discharge
        xlab: Days since hospitalization
      time_ICU:
        type: hospitalization
        distribution: lnormal
        formal_name: Time to ICU Admission
        xlab: Days since hospitalization
        xlim: [0,100]
      time_ICUdur:
        type: hospitalization
        distribution: lnormal
        formal_name: Time in ICU
        xlab: Days since ICU admission
        xlim: [0,100]
      time_death:
        type: hospitalization
        distribution: lnormal
        formal_name: Time to Death
        xlab: Days since hopitalization
      time_vent:
        type: hospitalization
        distribution: lnormal
        formal_name: Time to Ventilation
        xlab: Days since ICU admission
        xlim: [0,100]
  formatting:
    scenario_labels_short: ["WorstUncontrolled", "TestIsolate", "ModSocialDist"]
    scenario_labels:
    - Lockdown followed by Worst Case Uncontrolled Spread
    - Lockdown followed by Test and Isolate
    - Lockdown followed by Moderate Social Distancing
    scenario_colors: ["#D95F02", "#1B9E77", "#7570B3"]
    pdeath_labels: ["0.25% IFR", "0.5% IFR", "1% IFR"]
    display_dates: ["2020-06-01", "2020-07-01", "2020-08-01"]
    display_dates2: ["2020-07-01", "2020-08-01", "2020-09-01"]
